### PR TITLE
Step01 Conquer the bug with many ListView items

### PR DESCRIPTION
**Pull request by b01001011**
A bug has been found.
When the ListView has to deal with many items, the scrolling doen't really show expected items.
- [x] Refactor using a singleton object
- [x] Conquer the bug

### CODE REVIEW

**Comment by b01001011** [comment]
Not exactly know what caused the problem but I could say that the ListView contents were not updating due to this statement `if(convertView==null)`. Ready for a review!

**Comment by HQHAN** [comment]
@kwoolytech Utilizing convertview means it is reusing a list item view previously created, if you don't use convert view and keep creating the item view, it will end up being crashed if the no of list item goes over the limitation. Let's talk about this sometime at the office.

**Comment by b01001011** [comment]
Patch that we've made, is checked in. This PR should be ready to go.

**Comment by HQHAN** [comment]
Good to merge

**Pull request merged**
